name: Formatting

on: 
  pull_request: 
    branches:
      - main
      - master

jobs:
  autopep8:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .
      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'bharde@me.com'
          git commit -am "Automated autopep8 reformatting. See actions for more details"
          git push

  clang-format:
      name: clang-format Code Formatter
      runs-on: ubuntu-latest
      steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          ref: ${GITHUB_REF##*/}

      - name: install clang-format with npm
        uses: actions/setup-node@v2

      - name: Clang Code Formatter
        run: |
          echo "installing clang-format"
          npm install
          npm install clang-format
          echo "setting up git config"
          git config --global user.name 'Github Actions'
          git config --global user.email 'bharde@me.com'
          echo "finding c++ and arduino files"
          (git ls-tree --full-tree -r HEAD | grep -e "\.\(c\|h\|hpp\|cpp\|ino\)\$" | cut -f 2) > /tmp/temp.txt
          cat /tmp/temp.txt
          echo "formatting c++ and arduino files"
          cat /tmp/temp.txt | xargs -t -I % clang-format -i %
          rm /tmp/temp.txt
          echo "commiting formatted files and pushing"
          git add -A 
          git diff-index --quiet HEAD || git commit -m "Clang-format reformatting. See actions for more details"
          git diff-index --quiet HEAD || git push
