# TODO: change the action to what makes the most sense for avoiding future merge conflicts

name: Python Formatting

on: 
  pull_request: 
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  autopep8:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .
      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'bharde@me.com'
          git commit -am "Automated autopep8 fixes"
          git push

          name: "format code"
  clang-format:
      name: clang-format Code Formatter
      runs-on: ubuntu-latest
      steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: install clang-format with npm
        uses: actions/setup-node@v2

      - name: Clang Code Formatter
        run: |
          echo "installing clang-format"
          npm install
          npm install clang-format
          echo "setting up git config"
          git config user.name Brian
          git config user.email bharde@me.com
          echo "finding c++ and arduino files"
          SRC=$(git ls-tree --full-tree -r HEAD | grep -e "\.\(c\|h\|hpp\|cpp\|ino\)\$" | cut -f 2)
          echo $SRC
          echo "formatting c++ and arduino files"
          echo $SRC | xargs -t -I % clang-format -i %
          echo "commiting formatted files and pushing"
          git -A 
          git commit -m "Clang-format reformatting. See actions for more details"
          git push
